OnlineCarShop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
 path('admin/',admin.site.urls),
 path('cars/',include('cars.urls'))
]

cars/urls.py
from django.urls import path,include
from . import views
from  .views import RentalReviewFormView

app_name = 'cars'

urlpatterns = [
   path('list/',views.list,name='list'),
   path('add/',views.add,name='add'),
   path('delete/',views.delete,name='delete'),
   path('rental_review/',RentalReviewFormView.as_view(),name='rental_review'),
   path('thank_you/',views.thank_you,name='thank_you')
]

cars/models.py
from django.db import models
from django.core.validators import MinValueValidator ,MaxValueValidator

class CarModel(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
     return f"Car is {self.brand} {self.year}"


class Review (models.Model):
   first_name = models.CharField(max_length=30)
   last_name = models.CharField(max_length=30)
   stars = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])

cars/views.py
from django.shortcuts import render,redirect
from  django.urls import reverse,reverse_lazy
from django.views.generic import FormView
from . import models
from .form import ReviewForm


class RentalReviewFormView (FormView):
  form_class = ReviewForm
  template_name = 'car html/rental_review.html'
  success_url = reverse_lazy("cars:thank_you")
  def form_valid(self, form):
    form.save()
    return super().form_valid(form)



def list (request):

  all_cars = models.CarModel.objects.all()
  context = {"all_cars":all_cars}

  return  render(request ,'car html/list.html',context=context)

def add (request):
  if request.POST:
    brand = request.POST["brand"]

    year = int(request.POST["year"])

    models.CarModel.objects.create(brand=brand,year=year)

    return redirect(reverse("cars:list"))

  else:
      return  render(request ,'car html/add.html')

def delete (request):
  if request.POST:
    pk = request.POST["pk"]
    try:
      models.CarModel.objects.get(pk=pk).delete()
      return redirect(reverse("cars:list"))
    except:
      return redirect(reverse("cars:list"))
  else:
     return  render(request ,'car html/delete.html')

def rental_review (request):
  if request.POST:
    form = ReviewForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect(reverse("cars:thank_you"))
  else:
    form = ReviewForm()
  return render(request, 'car html/rental_review.html', context={'form':form} )

def thank_you (request):
  return render(request, 'car html/thank_you.html')

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
           <a class="nav-link" href="{% url 'cars:list' %}">List</a>
           <a class="nav-link" href="{% url 'cars:add' %}">Add</a>
           <a class="nav-link" href="{% url 'cars:delete' %}">Delete</a>
           <a class="nav-link" href="{% url 'cars:rental_review' %}">Rental_review</a>
    </div>
  </div>
</nav>
  {% block content %}
  {% endblock %}

</body>
</html>

templates/car html/add.html
{% extends "base.html" %}

{% block content %}

    <div>
       <h1> Add Car </h1>
        <h2> Add new car in Database </h2>
       <form action="" method="post" >
           {% csrf_token %}
           <div class="form-group" >
               <label for="brand" > Brand: </label>
               <input class="form-control" type="text" id="brand" name="brand">
           </div>

            <div class="form-group" >
               <label for="year" > Year: </label>
               <input class="form-control" type="text" is="year" name="year" >
           </div>
           <input class="btn btn-primary" type="submit" >

       </form>

    </div>



{% endblock %}

templates/car html/delete.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
       <h1> Delete Car </h1>
        <h2> Enter Pk to delete car </h2>
       <form action="" method="post" >
            {% csrf_token %}
           <div class="form-group" >
               <label for="pk" > PK number: </label>
               <input class="form-control" type="text" id="pk" name="pk">
           </div>
           <input class="btn btn-primary" type="submit" >
       </form>

    </div>

{% endblock %}

templates/car html/list.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
      <h1> List Car : </h1>
      <ul>
         {% for car in all_cars %}
            <li> {{car}} </li>
         {% endfor %}
     </ul>
  </div>


{% endblock %}

templates/car html/rental_review.html
{% extends "base.html" %}

{% block content %}

    <h2> rental_review </h2>
    <div class="container myform">
        <form action="" method="post" >
        {% csrf_token %}
         {% for field in form %}
           <div class="mb-3" >
             {{ field.label_tag }}
           </div>
           {{ field }}
           {{ field.errors }}
         {% endfor %}
     <input class="btn btn-primary" type="submit" >

    </form>
    </div>

{% endblock %}

templates/car html/thank_you.html
{% extends "base.html" %}

{% block content %}

    <h1> thank you </h1>

{% endblock %}

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
   {% if form.errors %}
     <p> your username or password was incorrect. try again </p>
   {% endif %}
    {% if next %}
         {% if user.is_authenticated %}
           <p> you dont have permission for this page </p>
         {% else %}
             <p> please login to see this page </p>
         {% endif %}

   {% endif %}
   <form method="post" action="{% url "login" %}" >
       {% csrf_token %}
       {{ form.username.label_tag }}
       {{ form.username }}

       {{ form.password.label_tag }}
       {{ form.password }}
    <input class="btn btn-primary" type="submit" value="login" >
   </form>
</body>
</html>